apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: observability

resources:
  - namespace.yaml
  - config.yaml
  - otel-agent
  - fluent-bit

commonLabels:
  observability.io/component: edge
  observability.io/architecture: federated
